
USE Library_db;


SELECT COUNT(*) AS TOTAL_BOOKS FROM BOOKS;
SELECT COUNT(*) AS TOTAL_MEMBERS FROM MEMBERS;
SELECT COUNT(*) AS TOTAL_BORROWINGS FROM BORROWING_RECORDS;
SELECT COUNT(*) AS UNRETURNED_BOOKS
FROM BORROWING_RECORDS
WHERE RETURN_DATE IS NULL;



SELECT MAX(AMOUNT) AS HIGHEST_FINE, MIN(AMOUNT) AS LOWEST_FINE FROM FINES;

SELECT TITLE, COPIES_AVAILABLE FROM BOOKS
WHERE COPIES_AVAILABLE = (SELECT MAX(COPIES_AVAILABLE) FROM BOOKS);

SELECT TITLE, COPIES_AVAILABLE FROM BOOKS
WHERE COPIES_AVAILABLE = (SELECT MIN(COPIES_AVAILABLE) FROM BOOKS);



SELECT ROUND(AVG(AMOUNT), 2) AS AVERAGE_FINE FROM FINES;
SELECT ROUND(AVG(COPIES_AVAILABLE), 2) AS AVG_COPIES_AVAILABLE FROM BOOKS;



SELECT
    M.FIRST_NAME,
    M.LAST_NAME,
    COUNT(BR.RECORD_ID) AS TOTAL_BORROWINGS
FROM MEMBERS M
LEFT JOIN BORROWING_RECORDS BR ON M.ID_MEMBERS = BR.ID_MEMBERS
GROUP BY M.ID_MEMBERS, M.FIRST_NAME, M.LAST_NAME
ORDER BY TOTAL_BORROWINGS DESC;

SELECT
    A.FIRST_NAME,
    A.LAST_NAME,
    COUNT(B.ID_BOOK) AS BOOKS_COUNT
FROM AUTHORS A
LEFT JOIN BOOKS B ON A.ID_AUTHOR = B.ID_AUTHOR
GROUP BY A.ID_AUTHOR, A.FIRST_NAME, A.LAST_NAME
ORDER BY BOOKS_COUNT DESC;

SELECT
    PAID,
    COUNT(*)    AS NUMBER_OF_FINES,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM FINES
GROUP BY PAID;



SELECT
    M.FIRST_NAME,
    M.LAST_NAME,
    COUNT(BR.RECORD_ID) AS TOTAL_BORROWINGS
FROM MEMBERS M
INNER JOIN BORROWING_RECORDS BR ON M.ID_MEMBERS = BR.ID_MEMBERS
GROUP BY M.ID_MEMBERS, M.FIRST_NAME, M.LAST_NAME
HAVING COUNT(BR.RECORD_ID) > 1
ORDER BY TOTAL_BORROWINGS DESC;

SELECT
    A.FIRST_NAME,
    A.LAST_NAME,
    SUM(B.COPIES_TOTAL) AS TOTAL_COPIES
FROM AUTHORS A
INNER JOIN BOOKS B ON A.ID_AUTHOR = B.ID_AUTHOR
GROUP BY A.ID_AUTHOR, A.FIRST_NAME, A.LAST_NAME
HAVING SUM(B.COPIES_TOTAL) > 4
ORDER BY TOTAL_COPIES DESC;



SELECT
    M.FIRST_NAME                    AS MEMBER_FIRSTNAME,
    M.LAST_NAME                     AS MEMBER_LASTNAME,
    COUNT(DISTINCT BR.RECORD_ID)    AS TOTAL_BORROWINGS,
    COUNT(DISTINCT F.FINE_ID)       AS TOTAL_FINES,
    SUM(F.AMOUNT)                   AS TOTAL_UNPAID_AMOUNT
FROM MEMBERS M
LEFT JOIN BORROWING_RECORDS BR ON M.ID_MEMBERS = BR.ID_MEMBERS
LEFT JOIN FINES F              ON BR.RECORD_ID  = F.RECORD_ID AND F.PAID = FALSE
GROUP BY M.ID_MEMBERS, M.FIRST_NAME, M.LAST_NAME
HAVING SUM(F.AMOUNT) > 0
ORDER BY TOTAL_UNPAID_AMOUNT DESC;
