
DROP DATABASE IF EXISTS Library_db;
CREATE DATABASE Library_db;
USE Library_db;


CREATE TABLE AUTHORS (
    ID_AUTHOR       INT             NOT NULL AUTO_INCREMENT,
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    EMAIL           VARCHAR(150)    UNIQUE,
    NATIONALITY     VARCHAR(100),
    PRIMARY KEY (ID_AUTHOR)
) ENGINE=InnoDB;


CREATE TABLE BOOKS (
    ID_BOOK             INT             NOT NULL AUTO_INCREMENT,
    ID_AUTHOR           INT             NOT NULL,
    TITLE               VARCHAR(254)    NOT NULL,
    PUBLISHER           VARCHAR(254),
    YEAR_PUBLISHED      INT,
    COPIES_TOTAL        INT             NOT NULL DEFAULT 1,
    COPIES_AVAILABLE    INT             NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_BOOK),
    CONSTRAINT FK_WRITTEN FOREIGN KEY (ID_AUTHOR)
        REFERENCES AUTHORS (ID_AUTHOR)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE TABLE MEMBERS (
    ID_MEMBERS          INT             NOT NULL AUTO_INCREMENT,
    FIRST_NAME          VARCHAR(100)    NOT NULL,
    LAST_NAME           VARCHAR(100)    NOT NULL,
    EMAIL               VARCHAR(150)    UNIQUE,
    PHONE               VARCHAR(20),
    MEMBERSHIP_DATE     DATE            NOT NULL DEFAULT (CURRENT_DATE),
    PRIMARY KEY (ID_MEMBERS)
) ENGINE=InnoDB;


CREATE TABLE BORROWING_RECORDS (
    RECORD_ID       INT     NOT NULL AUTO_INCREMENT,
    ID_BOOK         INT     NOT NULL,
    ID_MEMBERS      INT     NOT NULL,
    BORROW_DATE     DATE    NOT NULL DEFAULT (CURRENT_DATE),
    DUE_DATE        DATE    NOT NULL,
    RETURN_DATE     DATE    DEFAULT NULL,
    PRIMARY KEY (RECORD_ID),
    CONSTRAINT FK_CONCERNS FOREIGN KEY (ID_BOOK)
        REFERENCES BOOKS (ID_BOOK)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_PERFORMED FOREIGN KEY (ID_MEMBERS)
        REFERENCES MEMBERS (ID_MEMBERS)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE TABLE FINES (
    FINE_ID         INT             NOT NULL AUTO_INCREMENT,
    RECORD_ID       INT             NOT NULL UNIQUE,
    ID_MEMBERS      INT             NOT NULL,
    AMOUNT          DECIMAL(10,2)   NOT NULL,
    PAID            BOOLEAN         NOT NULL DEFAULT FALSE,
    FINE_DATE       DATE            NOT NULL DEFAULT (CURRENT_DATE),
    PRIMARY KEY (FINE_ID),
    CONSTRAINT FK_GENERATE FOREIGN KEY (RECORD_ID)
        REFERENCES BORROWING_RECORDS (RECORD_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_HAS FOREIGN KEY (ID_MEMBERS)
        REFERENCES MEMBERS (ID_MEMBERS)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;
