
USE library_db;


SELECT * FROM BOOKS;



SELECT TITLE, PUBLISHER, YEAR_PUBLISHED
FROM BOOKS
WHERE YEAR_PUBLISHED > 1960;



SELECT ID_MEMBERS, FIRST_NAME, LAST_NAME, MEMBERSHIP_DATE
FROM MEMBERS
ORDER BY LAST_NAME ASC;



SELECT TITLE, YEAR_PUBLISHED, PUBLISHER
FROM BOOKS
ORDER BY YEAR_PUBLISHED DESC
LIMIT 3;



SELECT TITLE, YEAR_PUBLISHED
FROM BOOKS
WHERE YEAR_PUBLISHED BETWEEN 1950 AND 1980;


SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM MEMBERS
WHERE FIRST_NAME LIKE 'A%';

SELECT TITLE, PUBLISHER
FROM BOOKS
WHERE PUBLISHER IN ('Gallimard', 'Présence Africaine', 'Seuil');



SELECT
    B.ID_BOOK,
    B.TITLE,
    B.YEAR_PUBLISHED,
    A.FIRST_NAME  AS AUTHOR_FIRST_NAME,
    A.LAST_NAME   AS AUTHOR_LAST_NAME
FROM BOOKS B
INNER JOIN AUTHORS A ON B.ID_AUTHOR = A.ID_AUTHOR
ORDER BY B.TITLE ASC;



SELECT
    M.ID_MEMBERS,
    M.FIRST_NAME,
    M.LAST_NAME,
    BR.RECORD_ID,
    BR.BORROW_DATE,
    BR.DUE_DATE
FROM MEMBERS M
LEFT JOIN BORROWING_RECORDS BR ON M.ID_MEMBERS = BR.ID_MEMBERS
ORDER BY M.ID_MEMBERS ASC;

SELECT
    M.FIRST_NAME                        AS MEMBER_FIRSTNAME,
    M.LAST_NAME                         AS MEMBER_LASTNAME,
    B.TITLE                             AS BOOK_TITLE,
    CONCAT(A.FIRST_NAME,' ',A.LAST_NAME) AS AUTHOR_FULLNAME,
    BR.BORROW_DATE,
    BR.DUE_DATE,
    BR.RETURN_DATE
FROM BORROWING_RECORDS BR
INNER JOIN MEMBERS M  ON BR.ID_MEMBERS = M.ID_MEMBERS
INNER JOIN BOOKS   B  ON BR.ID_BOOK    = B.ID_BOOK
INNER JOIN AUTHORS A  ON B.ID_AUTHOR   = A.ID_AUTHOR
ORDER BY BR.BORROW_DATE DESC;



SELECT
    M.FIRST_NAME,
    M.LAST_NAME,
    B.TITLE,
    BR.BORROW_DATE,
    BR.DUE_DATE
FROM BORROWING_RECORDS BR
INNER JOIN MEMBERS M ON BR.ID_MEMBERS = M.ID_MEMBERS
INNER JOIN BOOKS   B ON BR.ID_BOOK    = B.ID_BOOK
WHERE BR.RETURN_DATE IS NULL;

SELECT
    M.FIRST_NAME,
    M.LAST_NAME,
    B.TITLE,
    BR.RETURN_DATE
FROM BORROWING_RECORDS BR
INNER JOIN MEMBERS M ON BR.ID_MEMBERS = M.ID_MEMBERS
INNER JOIN BOOKS   B ON BR.ID_BOOK    = B.ID_BOOK
WHERE BR.RETURN_DATE IS NOT NULL
ORDER BY BR.RETURN_DATE DESC;
